### ISSUE TITLE
something wrong in run_example.sh

### ISSUE THREAD

**Issue by Flyfoxs** [allegro/allRank#12]
output and config-file-name  have something wrong in run_example.sh

old version:  docker run -e PYTHONPATH=/allrank -v $PROJECT_DIR:/allrank allrank:latest /bin/sh -c 'python allrank/data/generate_dummy_data.py && python allrank/main.py --config-file-name allrank/config.json --run-id test_run --output /allrank/test_run'

new version: docker run -e PYTHONPATH=/allrank  -v $PROJECT_DIR:/allrank allrank:latest /bin/sh -c 'python allrank/data/generate_dummy_data.py && python allrank/main.py --config-file-name ./scripts/local_config.json --run-id test_run   --job-dir  /allrank/test_run'

**Comment by PrzemekPobrotyn** [comment]
indeed, `job_dir` argument was renamed to `output` and the way the config file is read was changed. These changes were not reflected in the `run_example.sh` script. Fixing it not! Thank you for pointing out the problem.

**Comment by PrzemekPobrotyn** [comment]
next time, feel free to open a PR for such issues!
