### ISSUE TITLE
LambdaRank implementation in lambdaloss.py

### ISSUE THREAD

**Issue by mohuzi** [allegro/allRank#19]
I find a discrepancy between the loss formula in the paper and the LambdaRank's loss in lambdaloss.py.
![image](https://user-images.githubusercontent.com/2586132/92546116-cddde200-f21f-11ea-91ee-81c4bb6d55b0.png)
Is it true or am I missing anything?
Thank you.

**Comment by dmh43** [comment]
The implementation seems correct to me. I think you are missing a `sigmoid` in your definition of `scores_diffs` in the image you shared.

**Comment by mohuzi** [comment]
@dmh43  Thanks for the reply. The sigmoid is the σ sign in front of the `scores_diffs`. 
The correct implementation is the first equation in `LambdaRank`, but the equation in `Lambdaloss.py` is not equivalent to the `LambdaRank`, correct?

**Comment by dmh43** [comment]
Oh I see, I think there's some confusion on the notation. In the Burges paper that defines lambdarank, $\sigma$ is the growth rate parameter of the logistic function, not the function itself (scroll down further and it will become clear. Anyway it does not really make sense to take a sigmoid twice in a row (recall that `log(1+e^-x) = log sigmoid(x)`)).

**Comment by sadaharu-inugami** [comment]
Yes, we tried to keep close to the original paper. Unfortunately, sometimes it may lead to confusing notation. The sigma parameter is the exponent of the logistic function, just as @dmh43 wrote.

Thank you, it is very encouraging to see not only a new issue but also a solution coming from someone other than the original contributors.

**Comment by mohuzi** [comment]
All good now. Thanks for the clarification.

**Comment by dmh43** [comment]
@sadaharu-inugami You all did an incredible job with this codebase. Thanks so much for sharing it. Also the work on contextual ranking powered by this repo was also insightful to read.
