### ISSUE TITLE
Shape of the input of the Ordinal Loss

### ISSUE THREAD

**Issue by mohuzi** [allegro/allRank#20]
https://github.com/allegro/allRank/blob/c90b64a0c46e3f9101524f9c31533ecf1ebc8384/allrank/models/losses/ordinal.py#L28
Shouldn't the shape be `[batch_size, slate_length, n]` in here?
Thanks,

**Comment by PrzemekPobrotyn** [comment]
Yes, I believe you're right! Thanks for spotting this, will fix it soon.

**Comment by sadaharu-inugami** [comment]
Solved in [a32a9bc](https://github.com/allegro/allRank/commit/a32a9bc7468c6b190ec4a72ad3a475ab5b197aed). If that's all, you can close the issue now.
