### ISSUE TITLE
code for NeuralNDCG

### ISSUE THREAD

**Issue by zzchust** [allegro/allRank#22]
Recently, I read a paper about image retrieval, named [SmoothAP](https://github.com/Andrew-Brown1/Smooth_AP) aimed at optimizing neural network directly through AP metrics. It motives me to take this idea to  other metrics, such as NDCG. 

As you know， I have seen your paper NeuralNDCG [https://docs.mlinpl.org/virtual-event/2020/posters/37-NeuralNDCG_Direct_Optimisation_of_a_Ranking_Metric_via_Differentiable_Relaxation_of_Sorting.pdf](url).  I am so excited about this work.  It fully implemented what I am thinking about.

I cant waited to use it in my task, would you mind to share this code to me ! 

sincere thanks！

**Comment by sadaharu-inugami** [comment]
Thank you for your kind words. We are currently discussing the code release so it should be available in the near future (let's say, a few weeks).

**Comment by sadaharu-inugami** [comment]
NeuralNDCG has been released in [1.4 version](https://github.com/allegro/allRank/pull/24).
