### ISSUE TITLE
What is the meaning of slate?

### ISSUE THREAD

**Issue by hosseinfani** [allegro/allRank#29]

**Comment by PrzemekPobrotyn** [comment]
Slate is another term for a group of items to be ranked. In ranking setting a slate with ground truth relevance scores can be thought of as a single training example.

**Comment by PrzemekPobrotyn** [comment]
We decided to use that term following the paper Seq2Slate: Re-ranking and Slate Optimization with RNNs by Bello et al.

**Comment by hosseinfani** [comment]
Thank you for the explanation.
