### ISSUE TITLE
Example to run listNet

### ISSUE THREAD

**Issue by sahilm1992** [allegro/allRank#38]
Is there any example on how to run the ListNet module?

**Comment by sahilm1992** [comment]
Also is the code of Listnet correct?

**Comment by sadaharu-inugami** [comment]
The code of Listnet is correct, it is a vanilla implementation of the formula (2) in the paper [Learning to Rank: From Pairwise Approach to Listwise Approach](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/tr-2007-40.pdf).

As for the example, you could modify the local config `scripts/local_config.json` and run the example script `scripts/run_in_docker.sh`, remembering about building the docker image first (`docker build -t allrank:latest .` from the main directory).

**Comment by sahilm1992** [comment]
Thank you :)
