### ISSUE TITLE
Location of loss functions??

### ISSUE THREAD

**Issue by SourabhRanade** [allegro/allRank#48]
Hello, thank you for all the efforts taken to develop this library. I wanted to see the implementation of all the losses. I tried searching but could not find the exact location in the repository. I was particularly interested in the lambda loss. Could you please guide me to it.

**Comment by mhsyno** [comment]
Hello,
All the code concerning loss functions is located here: https://github.com/allegro/allRank/tree/master/allrank/models/losses

Regards,
Mikołaj

**Comment by SourabhRanade** [comment]
Thanks a lot!!
