### ISSUE TITLE
AssertionError: val ndcg_5 got 0.7586661577224731. It was expected to be at least 0.76

### ISSUE THREAD

**Issue by metin-akyol** [allegro/allRank#52]
Running the examples throws this error: Can this be ignored? Since this is is dummy data?

AssertionError: val ndcg_5 got 0.7586661577224731. It was expected to be at least 0.76

**Comment by kretes** [comment]
Yes, I think that given the small discrepancy 0.758 vs expected 0.76 this can be ignored. 
I think this check isn't robust enough and it might happen it fails accidentally

**Comment by metin-akyol** [comment]
Thank you for clarifying this, I appreciate it.
