### ISSUE TITLE
Question about positional encoding

### ISSUE THREAD

**Issue by rena9155** [allegro/allRank#67]
Can you provide some guidance on positional encoding? What should I put for 'positional_coding' in the config file, and how can I include the original ranking as part of the input data? Also can you provide some explanations on 'Fixed positional encoding' and 'Learnable positional encoding'? Many Thanks!

**Comment by kretes** [comment]
Hello.
Regarding overall explanation about positional encodings - please refer to our paper https://arxiv.org/pdf/2005.10084 and chapters 4.4 and 5.5 most importantly.

Technically - in the config - you need to provide:
```
"positional_encoding": {
 "strategy": "fixed",  # (or 'learned')
 "max_indices": 50 # or some other value - eq or larger than max length slates in the dataset
}

**Comment by rena9155** [comment]
Thank you!
